### ISSUE TITLE
lack model_weight when use docker

### ISSUE THREAD

**Issue by Bennyggcc** [hms-dbmi/CHIEF#27]
After running cammand 'docker pull chiefcontainer/chief:v1.11, docker run --rm -it --entrypoint /bin/bash chiefcontainer/chief:v1.11'

Use docker to run code, it gives the error as follow:
root@e88d30af6313:/# git clone https://github.com/hms-dbmi/CHIEF.git
root@e88d30af6313:/# cd CHIEF
root@e88d30af6313:/CHIEF# python3 Get_CHIEF_patch_feature.py

Traceback (most recent call last):
  File "Get_CHIEF_patch_feature.py", line 20, in <module>
    td = torch.load(r'./model_weight/CHIEF_CTransPath.pth')
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model_weight/CHIEF_CTransPath.pth'

It still needs to download model weight if using docker?

**Comment by Dadatata-JZ** [comment]
@Bennyggcc Benny, 

you can also find all weights from our G-cloud disk.
https://drive.google.com/drive/u/1/folders/1uRv9A1HuTW5m_pJoyMzdN31bE1i-tDaV

**Comment by starquest-1** [comment]
Hello! Hello! Congratulations on what you have achieved now！
 In the IDH reproduction task, I didn't find the IDH weight file in file ./Downstream/Biomaker/classification_eval.py, which appears on line 37 of the code, referencing the code for you as “model.load_state_dict(torch.load('./weights/IDH/s_'+str(i)+'_checkpoint.pt'))”.
I look forward to hearing from you, thank you very much!

**Comment by lai524746** [comment]
Hello! Thank you for sharing the code！ However, I encountered the same issue where I couldn't find the IDH weight file in the Biomarker task, resulting in the following error when running classification_eval.py: "FileNotFoundError: [Errno 2] No such file or directory: './weights/IDH/s_0_checkpoint.pt' ". If possible, could I seek your help to resolve this issue? I look forward to your response. Thank you！

**Comment by Jimmyli9** [comment]
@Dadatata-JZ  Same issue here, I couldn't find the IDH weight file in the Biomarker task, resulting in the following error when running classification_eval.py: "FileNotFoundError: [Errno 2] No such file or directory: './weights/IDH/s_0_checkpoint.pt' ". Please let me know if I missed something
