### ISSUE TITLE
how to get ./Downstream/Tumor_origin/src/feature/tcga/TCGA-LN-A8I1-01Z-00-DX1.F2C4FBC3-1FFA-45E9-9483-C3F1B2B7EF2D.pt

### ISSUE THREAD

**Issue by 27yw** [hms-dbmi/CHIEF#41]
Hi! very wonderful work.
Here comes some question
how to get ./Downstream/Tumor_origin/src/feature/tcga/TCGA-LN-A8I1-01Z-00-DX1.F2C4FBC3-1FFA-45E9-9483-C3F1B2B7EF2D.pt

when I try to run this code 
` python3 Get_CHIEF_WSI_level_feature_batch.py`

and I got this error
`Original Traceback (most recent call last):
  File "/data_train/code/biz/yw/miniconda3/envs/chief2/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/data_train/code/biz/yw/miniconda3/envs/chief2/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    data = self.dataset[possibly_batched_index]
  File "/data_train/code/biz/yw/CHIEF/datasets/BagDataset.py", line 25, in __getitem__
    features = torch.load(full_path, map_location=torch.device('cpu'))
  File "/data_train/code/biz/yw/miniconda3/envs/chief2/lib/python3.9/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/data_train/code/biz/yw/miniconda3/envs/chief2/lib/python3.9/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data_train/code/biz/yw/miniconda3/envs/chief2/lib/python3.9/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './Downstream/Tumor_origin/src/feature/tcga/TCGA-B6-A0WV-01Z-00-DX1.A8B9E114-A8CF-4389-B47C-2E1B842F7FF9.pt'`
how to fix it?

**Comment by 27yw** [comment]
btw there is no feature/tcga folder under Downstream/Tumor_origin/src/

**Comment by Dadatata-JZ** [comment]
@27yw thanks. 

It is just intended to show how to load a feature file. It is really nothing technical. 
You should (1) tile your WSIs, (2) extract tile-level features (3) stack the features as a matrix in a file (e.g., pickle).

**Comment by 27yw** [comment]
HI thanks for your answering
so you use this repo to get the features and save into a .pt file?
https://github.com/Xiyue-Wang/TransPath

**Comment by ivicts** [comment]
@Dadatata-JZ  Hi for survial, inference.ipynb, may I ask if the feature file is tile-level features (Get_CHIEF_patch_feature.py) or WSI level features (Get_CHIEF_WSI_level_feature.py)?

**Comment by ivicts** [comment]
@Dadatata-JZ Thanks, I just want to run the inference.ipynb, for the survival problem for my custom data. For this problem, what are the input features? Is it:

1. Tile-level features (Get_CHIEF_patch_feature.py)
2. WSI level features (Get_CHIEF_WSI_level_feature.py)
3.  (a) Tile my WSIs
(b) Extract tile-level features (Get_CHIEF_patch_feature.py)
(c) Stack the features as a matrix in a file (e.g., pickle, concatenate? what dimension?). 

Which one should I do? I just want to run the survival analysis for my custom data.

**Comment by ivicts** [comment]
@Dadatata-JZ are there any updates on this?

**Comment by ivicts** [comment]
@Dadatata-JZ Hello, I sent an email to Kun-Hsing_Yu@hms.harvard.edu and xiyue.wang.scu@gmail.com last week but haven't received a reply. The email title is "Applying CHIEF on our lung cancer data for survival analysis".
