### ISSUE TITLE
Patch_level extract

### ISSUE THREAD

**Issue by Tuner12** [hms-dbmi/CHIEF#45]
model = ctranspath()
model.head = nn.Identity()
td = torch.load(r'./model_weight/CHIEF_CTransPath.pth')
model.load_state_dict(td['model'], strict=True)

when the strict = True,there are some keys missing:
RuntimeError: Error(s) in loading state_dict for SwinTransformer:
        Missing key(s) in state_dict: "patch_embed.proj.weight", "patch_embed.proj.bias". 
        Unexpected key(s) in state_dict: "patch_embed.proj.0.weight", "patch_embed.proj.1.weight", "patch_embed.proj.1.bias", "patch_embed.proj.1.running_mean", "patch_embed.proj.1.running_var", "patch_embed.proj.1.num_batches_tracked", "patch_embed.proj.3.weight", "patch_embed.proj.4.weight", "patch_embed.proj.4.bias", "patch_embed.proj.4.running_mean", "patch_embed.proj.4.running_var", "patch_embed.proj.4.num_batches_tracked", "patch_embed.proj.6.weight", "patch_embed.proj.6.bias". 

But if I set false,then the model works and print [1,768] normally.

Btw,from timm.models.layers.helpers import to_2tuple,this method is outdated version，if I use the latest timm, from timm.layers.helpers import to_2tuple,there is some error in init: missing strict_img_size and output_fmt.

**Comment by Dadatata-JZ** [comment]
@Tuner12 

Yes, as we have specified the timm version. At one point, timm underwent a significant update. We always used "strict=True" and never met this issue. 

For the tile-level extractor, you can also follow the instruction in here. 
https://github.com/Xiyue-Wang/TransPath

**Comment by Jonyyqn** [comment]
I also get the same Error, when I set strict=True. The version of timm is 0.5.4, which is same as in the requirements.txt

**Comment by Jonyyqn** [comment]
I get the same Error. The version of timm is 0.5.4, which is instralled through pip.

**Comment by Jonyyqn** [comment]
When I try the command "pip install timm-0.5.4.tar", I get the Error as follows:
```
i
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by guofeng97** [comment]
@Jonyyqn I had the same problem once, maybe you can try using the 'build ' tool. pip install build

**Comment by Jonyyqn** [comment]
> @Jonyyqn I had the same problem once, maybe you can try using the 'build ' tool. pip install build

Thx

**Comment by Yuchen-Li** [comment]
Anyone have the solution? Met the same issue.
'''
Traceback (most recent call last):
  File "Get_CHIEF_patch_feature.py", line 21, in <module>
    model.load_state_dict(td['model'], strict=True)
  File "/opt/conda/envs/chief/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SwinTransformer:
        Missing key(s) in state_dict: "patch_embed.proj.weight", "patch_embed.proj.bias". 
        Unexpected key(s) in state_dict: "patch_embed.proj.0.weight", "patch_embed.proj.1.weight", "patch_embed.proj.1.bias", "patch_embed.proj.1.running_mean", "patch_embed.proj.1.running_var", "patch_embed.proj.1.num_batches_tracked", "patch_embed.proj.3.weight", "patch_embed.proj.4.weight", "patch_embed.proj.4.bias", "patch_embed.proj.4.running_mean", "patch_embed.proj.4.running_var", "patch_embed.proj.4.num_batches_tracked", "patch_embed.proj.6.weight", "patch_embed.proj.6.bias". 
'''

**Comment by shadow0901** [comment]
> Anyone have the solution? Met the same issue. ''' Traceback (most recent call last): File "Get_CHIEF_patch_feature.py", line 21, in model.load_state_dict(td['model'], strict=True) File "/opt/conda/envs/chief/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for SwinTransformer: Missing key(s) in state_dict: "patch_embed.proj.weight", "patch_embed.proj.bias". Unexpected key(s) in state_dict: "patch_embed.proj.0.weight", "patch_embed.proj.1.weight", "patch_embed.proj.1.bias", "patch_embed.proj.1.running_mean", "patch_embed.proj.1.running_var", "patch_embed.proj.1.num_batches_tracked", "patch_embed.proj.3.weight", "patch_embed.proj.4.weight", "patch_embed.proj.4.bias", "patch_embed.proj.4.running_mean", "patch_embed.proj.4.running_var", "patch_embed.proj.4.num_batches_tracked", "patch_embed.proj.6.weight", "patch_embed.proj.6.bias". '''

"Did you solve it?"
